# Generated by Django 4.1.4 on 2023-05-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_facture_rename_produits_produit_delete_factures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=25)),
                ('Prenom', models.TextField()),
                ('Telephone', models.CharField(max_length=8)),
                ('Achats', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='approvision',
            name='Quantite',
            field=models.IntegerField(default=1),
        ),
    ]
