# Generated by Django 4.1.4 on 2023-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_alter_produit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvision',
            name='Pointure',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='Pointure',
        ),
        migrations.AddField(
            model_name='facture',
            name='Quantite',
            field=models.IntegerField(default=1),
        ),
    ]
