# Generated by Django 4.1.4 on 2023-05-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_alter_facture_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='id',
            new_name='Id',
        ),
    ]
