# Generated by Django 4.1.4 on 2023-05-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_rename_id_facture_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='Id',
            new_name='Numero',
        ),
    ]
