# Generated by Django 4.1.4 on 2023-05-08 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0010_rename_numero_facture_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='date_added',
            new_name='date_et_heure',
        ),
    ]
