# Generated by Django 4.1.4 on 2023-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0011_rename_date_added_facture_date_et_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Lieu',
            field=models.TextField(default='Boutique'),
        ),
    ]
