# Generated by Django 4.1.4 on 2023-05-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0012_facture_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Intervention',
            field=models.IntegerField(default=1),
        ),
    ]
