# Generated by Django 4.1.4 on 2023-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0014_rename_intervention_client_interventions'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Prix',
            field=models.IntegerField(default=8500),
        ),
    ]
