# Generated by Django 4.1.4 on 2023-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0015_produit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Prix',
            field=models.IntegerField(default=1),
        ),
    ]
