# Generated by Django 4.1.4 on 2023-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0016_facture_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='Couleur',
            field=models.CharField(default='Rouge', max_length=15),
        ),
        migrations.AddField(
            model_name='produit',
            name='Pointure',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='produit',
            name='Name',
            field=models.CharField(max_length=15),
        ),
    ]
