# Generated by Django 4.1.4 on 2023-05-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0017_produit_couleur_produit_pointure_alter_produit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='Couleur',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='Pointure',
        ),
    ]
