# Generated by Django 4.1.4 on 2023-05-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0018_remove_produit_couleur_remove_produit_pointure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='Prix',
            new_name='Montant',
        ),
    ]
