# Generated by Django 4.1.4 on 2023-05-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0019_rename_prix_facture_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureTemporaire',
            fields=[
                ('No', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=25)),
                ('Prenom', models.TextField()),
                ('Telephone', models.CharField(max_length=8)),
                ('Quantite', models.IntegerField(default=1)),
                ('Montant', models.IntegerField(default=1)),
                ('Lieu', models.TextField(default='Boutique')),
                ('Statut', models.CharField(default='non livré', max_length=15)),
                ('date_et_heure', models.DateTimeField(auto_now=True)),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_temporaires', to='Gestion.produit')),
            ],
            options={
                'verbose_name': 'Facture Temporaire',
                'verbose_name_plural': 'Factures Temporaires',
                'ordering': ['-date_et_heure'],
            },
        ),
    ]
