# Generated by Django 4.1.4 on 2023-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0021_alter_facturetemporaire_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturetemporaire',
            name='Livreur',
            field=models.CharField(choices=[('Adama', 'Adama'), ('Mohamed', 'mohamed')], default='non livre', max_length=10),
        ),
    ]
