# Generated by Django 4.1.4 on 2023-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0022_facturetemporaire_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturetemporaire',
            name='Livreur',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Adama', 'Adama'), ('Mohamed', 'mohamed')], default='En cours', max_length=10),
        ),
    ]
