# Generated by Django 4.1.4 on 2023-05-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0023_alter_facturetemporaire_livreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Livreur',
            field=models.CharField(choices=[('Adama', 'Adama'), ('Mohamed', 'mohamed')], default='En cours', max_length=10),
        ),
    ]
