# Generated by Django 4.1.4 on 2023-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0024_facture_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Livreur',
            field=models.CharField(choices=[('Boutique', 'Boutique'), ('Adama', 'Adama'), ('Mohamed', 'mohamed')], default='Boutique', max_length=10),
        ),
    ]
