# Generated by Django 4.1.4 on 2023-05-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0025_alter_facture_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturetemporaire',
            name='Statut',
            field=models.CharField(choices=[('non livre', 'Non livré'), ('livre', 'Livre'), ('Annule', 'Annule')], default='non livre', max_length=10),
        ),
    ]
