# Generated by Django 4.1.4 on 2023-05-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0026_alter_facturetemporaire_statut'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FactureTemporaire',
            new_name='Commandes',
        ),
    ]
