# Generated by Django 4.1.4 on 2023-05-24 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0027_rename_facturetemporaire_commandes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandes',
            options={'ordering': ['-date_et_heure'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
    ]
