# Generated by Django 4.1.4 on 2023-05-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0028_alter_commandes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motif', models.TextField()),
                ('Montant', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
