# Generated by Django 4.1.4 on 2023-05-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0029_depenses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depenses',
            new_name='Depense',
        ),
    ]
