# Generated by Django 4.1.4 on 2023-06-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0030_rename_depenses_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvision',
            name='montant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='Gestion.produit'),
        ),
    ]
