# Generated by Django 4.1.4 on 2023-06-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0031_approvision_montant_alter_commandes_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvision',
            old_name='montant',
            new_name='Montant',
        ),
    ]
