# Generated by Django 4.1.4 on 2023-07-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0032_rename_montant_approvision_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandes',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.produit'),
        ),
    ]
