# Generated by Django 4.1.4 on 2023-07-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0033_alter_commandes_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='Gestion.produit'),
        ),
    ]
