# Generated by Django 4.1.4 on 2023-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0034_alter_facture_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='Payer',
            field=models.CharField(choices=[('non livre', 'Non livré'), ('livre', 'Livre'), ('Annule', 'Annule')], default='NON', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='Livreur',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='En cours', max_length=10),
        ),
    ]
