# Generated by Django 4.1.4 on 2023-07-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0035_commandes_payer_alter_commandes_livreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepensePrivees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Motif', models.TextField()),
                ('Montant', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commandes',
            name='Livreur',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Adama', 'Adama'), ('Mohamed', 'mohamed')], default='En cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='Payer',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='NON', max_length=10),
        ),
    ]
