# Generated by Django 4.1.4 on 2023-07-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0036_depenseprivees_alter_commandes_livreur_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DepensePrivees',
            new_name='DepensePrivee',
        ),
    ]
