# Generated by Django 4.1.4 on 2023-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0038_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='Livreur',
            field=models.CharField(default='Boutique', max_length=10),
        ),
    ]
