# Generated by Django 4.1.4 on 2023-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0041_alter_commandes_payer_alter_produit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='Rabais',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandes',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
