# Generated by Django 4.1.4 on 2023-07-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0042_commandes_rabais_commandes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='Rabais',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facture',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
