# Generated by Django 4.1.4 on 2023-09-21 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0043_facture_rabais_facture_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_et_heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
