# Generated by Django 4.1.4 on 2023-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0044_alter_facture_date_et_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='Equipe',
            field=models.CharField(choices=[('equipe01', 'equipe01'), ('equipe 02', 'equipe 02')], default='equipe01', max_length=10),
        ),
        migrations.AddField(
            model_name='facture',
            name='Equipe',
            field=models.CharField(choices=[('equipe01', 'equipe01'), ('equipe 02', 'equipe 02')], default='equipe01', max_length=10),
        ),
    ]
